apiVersion: v1
kind: Service
metadata:
  name: image-stubber
  namespace: {{ .Values.namespace }}
  labels:
    app: image-stubber
spec:
  selector:
    app: image-stubber
  ports:
    - name: http
      port: 80
